version: '3.7'
services:
  database:
    image: postgres:14.5-alpine3.16
    container_name: database
    restart: always
    env_file:
      - docker.env
    ports:
      - "5432:5432"
    networks:
      - mi_red
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
  spring-app:
    build:
      context: .
      args:
        - MAVEN_OPTS=-DskipTests=true
    container_name: spring-app
    ports:
      - "8080:8080"
    networks:
      - mi_red
    depends_on:
      database:
        condition: service_healthy
networks:
  mi_red:
